CodastroProdutos/Models/Base.cs
namespace CodastroProdutos.Models
{
    public class Base
    {
        public string Nome { get; set; }
    }
}

CodastroProdutos/Models/Categoria.cs
namespace CodastroProdutos.Models
{
    public class Categoria : Base 
    {
        public int CategoriaId { get; set; } 
        
    }
}

CodastroProdutos/Models/ErrorViewModel.cs
namespace CodastroProdutos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodastroProdutos/Models/Fornecedores.cs
namespace CodastroProdutos.Models
{
    public class Fornecedores : Base 
    {
        public int FornecedorId { get; set; }
        public int Telefone { get; set; }
        public string Site { get; set; }

    }
}

CodastroProdutos/Models/Produtos.cs
namespace CodastroProdutos.Models
{
    public class Produtos : Base 
    {
        public int ProdutosId { get; set; }
        public decimal Preco {  get; set; }
        public  int QuantidadeDisponivel {  get; set; }
        public Ecor Cor { get; set; }
        public int Potencia { get; set; }

    }
    public enum Ecor 
    { 
        Branco = 1,
        Preto = 2,
        cinza = 3,
        roxo = 4,

    }


}

CodastroProdutos/Controllers/CategoriaController.cs
using CodastroProdutos.Data;
using CodastroProdutos.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodastroProdutos.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly Context context;
        public CategoriaController() 
        {  
            context = new Context();
        
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()    
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Categoria categoria) 
        {
            context.Categorias.Add(categoria);
            context.SaveChanges();
            return View(categoria);
         
        }
        
    }
}

CodastroProdutos/Controllers/HomeController.cs
using CodastroProdutos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CodastroProdutos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodastroProdutos/Controllers/ProdutoController.cs
using CodastroProdutos.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CodastroProdutos.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: ProdutoController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ProdutoController/Details/5
        public ActionResult Details(int ProdutosId)
        {
            return View();
        }

        // GET: ProdutoController/Create
        public ActionResult Create() 
        {
            return View();
        }

        // POST: ProdutoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Produtos produtos)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProdutoController/Edit/5
        public ActionResult Edit(int ProdutosId)
        {
            return View();
        }

        // POST: ProdutoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int ProdutosId, Produtos produtos)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProdutoController/Delete/5
        public ActionResult Delete(int ProdutosId) 
        {
            return View();
        }

        // POST: ProdutoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int ProdutosId, Produtos produtos)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CodastroProdutos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodastroProdutos/Views/Produto/Create.cshtml
@model CodastroProdutos.Models.Produtos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProdutosId" class="control-label"></label>
                <input asp-for="ProdutosId" class="form-control" />
                <span asp-validation-for="ProdutosId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeDisponivel" class="control-label"></label>
                <input asp-for="QuantidadeDisponivel" class="form-control" />
                <span asp-validation-for="QuantidadeDisponivel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cor" class="control-label"></label>
                <input asp-for="Cor" class="form-control" />
                <span asp-validation-for="Cor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Potencia" class="control-label"></label>
                <input asp-for="Potencia" class="form-control" />
                <span asp-validation-for="Potencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CodastroProdutos/Views/Produto/Delete.cshtml
@model CodastroProdutos.Models.Produtos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutosId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutosId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantidadeDisponivel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantidadeDisponivel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Potencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Potencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CodastroProdutos/Views/Produto/Details.cshtml
@model CodastroProdutos.Models.Produtos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutosId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutosId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantidadeDisponivel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantidadeDisponivel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Potencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Potencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

CodastroProdutos/Views/Produto/Edit.cshtml
@model CodastroProdutos.Models.Produtos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProdutosId" class="control-label"></label>
                <input asp-for="ProdutosId" class="form-control" />
                <span asp-validation-for="ProdutosId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeDisponivel" class="control-label"></label>
                <input asp-for="QuantidadeDisponivel" class="form-control" />
                <span asp-validation-for="QuantidadeDisponivel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cor" class="control-label"></label>
                <input asp-for="Cor" class="form-control" />
                <span asp-validation-for="Cor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Potencia" class="control-label"></label>
                <input asp-for="Potencia" class="form-control" />
                <span asp-validation-for="Potencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CodastroProdutos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodastroProdutos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodastroProdutos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodastroProdutos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                </div>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Produtos
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" asp-area="" asp-controller="Produto" asp-action="Create">Criar</a>
                        <li><a class="dropdown-item" asp-area="" asp-controller="Produto" asp-action="Details">aaa</a>
                        <li><a class="dropdown-item" asp-area="" asp-controller="Produto" asp-action="Delete">Apagar</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CodastroProdutos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>